version: '3.1'

services:
  text-sentiment-analysis-postgres:
    container_name: text-sentiment-analysis-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: s5f98d2eg1t8b53d6gc91fd4g7
      POSTGRES_DB: text-sentiment-analysis
      POSTGRES_PASSWORD: b8b2c468625df4g8b2ebb7dd49521395
    ports:
      - "5438:5432"
    volumes:
      - ./data/data:/var/lib/postgresql/data